cache:
    - ccache
    - directories:
        - $HOME/brew-cache
notifications:
    email: false
language: cpp
services:
    - docker
matrix:
  include:
    - os: linux
      dist: trusty
      env:
          - DOCKER_TAG=ubuntu1604
          - DOCKER_NAME="Ubuntu 16.04"
    - os: linux
      dist: trusty
      env:
          - DOCKER_TAG=cross-qemu-rpistretch
          - DOCKER_NAME="Raspberry Pi"
    - os: osx
      osx_image: xcode7.3
      env:
        - HOMEBREW_CACHE=$HOME/brew-cache
before_install:
    - ./.travis/travis_install.sh
script:
    - ./.travis/travis_build.sh
after_success:
    - ./.travis/travis_deploy.sh
